### ISSUE TITLE
How to import (source,target) pairs into the project?

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#10]
I have a list of (source,target) sentence pairs and I want to build an encoder-decoder from scratch. It seems that the nmt.py is based on standard datasets in machine translation and specific inputs (datasets and dictionaries) are required. 
**what is the best way to feed (source,target) pairs?**

**Comment by orhanf** [comment]
@amirj i think the easiest way for you is preparing two files with your data, having a sentence per line. 
Then you can use [this](https://github.com/kyunghyuncho/dl4mt-material/blob/master/data/build_dictionary.py) script to extract dictionaries from those files. Or you can replace the iterator, making it return (source, target) pairs as you prefer.

**Comment by amirj** [comment]
@orhanf thank you for your quick response.
