### ISSUE TITLE
By RNN Encoded,how to learn without exactly output vector???

### ISSUE THREAD

**Issue by astrung** [kyunghyuncho/dl4mt-material#11]
By this tutorial:http://devblogs.nvidia.com/parallelforall/introduction-neural-machine-translation-gpus-part-2/.
i see that output of RNN Encoded depends on Matrix weight and Matrix input ( tanh function ), and when we learn with training data,this matrix is always changed>>So we can not have an exactly output when model is training ( with Encoded RNN ) .So how to learn weights and bias for RNN Encoded??Do we need a backpropagation from RNN Decoded to RNN Encoded to change weights and bias for RNN Encoded???Or by some other ways???

**Comment by kyunghyuncho** [comment]
Yes, the encoder is trained together with the decoder to maximize translation quality.
