### ISSUE TITLE
Any accompanying slides? 

### ISSUE THREAD

**Issue by jli05** [kyunghyuncho/dl4mt-material#13]
Just wondering if there're any slides that'd make the code even clearer. Thanks in advance.

**Comment by vince62s** [comment]
right, also I am unclear is a GPU required code-wise or can we train with multiple servers through SGE ?

**Comment by Franck-Dernoncourt** [comment]
The code was part of the [DL4MT (Deep Learning for Machine Translation) Winter School 2015](http://dl4mt.computing.dcu.ie/#/schedule) that took place two months ago, but it looks like no materials other than the code has been released so far.

http://www.kyunghyuncho.me/home/courses/ds-ga-3001-fall-2015 has some relevant content though (e.g.  [Introduction to Neural Machine Translation with GPUs](http://devblogs.nvidia.com/parallelforall/introduction-neural-machine-translation-with-gpus/) and [Natural Language Understanding with Distributed Representation](http://arxiv.org/abs/1511.07916)), perhaps the same materials were used there.

I agree that a basic readme wouldn't hurt.
