### ISSUE TITLE
How to encode an input text?

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#14]
I have trained a simple encoder-decoder model (session 1). Everything is OK and I can generate translation using translate.py
I'm interested to **encode** the input text using RNN model. Would you please help me?

**Comment by jli05** [comment]
Would you mind doing a Pull Request of what you did to make the code run?

**Comment by kyunghyuncho** [comment]
I just added encode.py in session1: https://github.com/kyunghyuncho/dl4mt-material/blob/master/session1/encode.py
