### ISSUE TITLE
GRU attention with 2 step process - seesion 2

### ISSUE THREAD

**Issue by karesh** [kyunghyuncho/dl4mt-material#16]
First you computed the hidden activation as the normal gru layer (h1). Then adding context information to another set of gru computation to get the final output of h2. 
Could you site the reference for the GRU attention equations in session 2 ? Or any reason to that ?

**Comment by kyunghyuncho** [comment]
Please, see Bahdanau et al. (2015): NEURAL MACHINE TRANSLATION
BY JOINTLY LEARNING TO ALIGN AND TRANSLATE.
