### ISSUE TITLE
reload training has unpredictable error

### ISSUE THREAD

**Issue by jakezhaojb** [kyunghyuncho/dl4mt-material#17]
When setting `reload` to `True`, it has unpredictable error during validation error calculation. Traceback showed below: 

``` python
Traceback (most recent call last):
  File "train_nmt.py", line 51, in <module>
    'reload': [True]})
  File "train_nmt.py", line 32, in main
    use_dropout=params['use-dropout'][0])
  File "/home/jz1672/Projects/charNMT/archive/CN_EN/2015_1203_cn_en_conv3x256_gru_unseg/nmt.py", line 1320, in train
    bad_counter += 1
UnboundLocalError: local variable 'bad_counter' referenced before assignment
```

**Comment by orhanf** [comment]
i guess [this](https://github.com/kyunghyuncho/dl4mt-material/blob/master/session2/nmt.py#L1126) should be `bad_counter` not `bad_count`

**Comment by bastings** [comment]
Yes, it should be `bad_counter`.So it was actually really bad ;-)

**Comment by jakezhaojb** [comment]
Agree guys. Will make a pull request soon!
