### ISSUE TITLE
Multiple translation for a single input

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#25]
It is well known in the field of translation that a single sentence has multiple translations. Although current translation corpora don't support this feature but I think it is better if the tools support this feature.
Training data contains an input sentence and a **list** of corresponding translations. During training the model, the output of decoder is compared with all possible translations and the minimum cost will be back-propagated,

**Comment by orhanf** [comment]
@amirj we already have the tools to do that, you can use [translate.py](https://github.com/kyunghyuncho/dl4mt-material/blob/master/session3/translate.py) from session3. It has an `n_best` option that you can specify to generate multiple translations (with their scores).

**Comment by amirj** [comment]
Please check the following: https://github.com/kyunghyuncho/dl4mt-material/issues/30
