### ISSUE TITLE
Is it possible to train a deep bidirectional RNNs?

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#26]
I just interested to know if it is possible to stack multiple layers of bidirectional RNNs using this project?

**Comment by kyunghyuncho** [comment]
Yes, it is indeed possible. You simply need to define multiple encoders and stack them onto one another:

https://github.com/kyunghyuncho/dl4mt-material/blob/master/session2/nmt.py#L593-L595

**Comment by amirj** [comment]
It's great.
Would you please give me more details?
For example, how to define a two layer bidirectional attention-based network?

**Comment by amirj** [comment]
Any help?

**Comment by orhanf** [comment]
Crudely, you should do something like:

``` python
    # word embedding for forward rnn (source)
    emb = tparams['Wemb'][x.flatten()]
    emb = emb.reshape([n_timesteps, n_samples, options['dim_word']])
    proj1 = get_layer(options['encoder'])[1](tparams, emb, options,
                                             prefix='encoder_1st',
                                             mask=x_mask)


    # second layer rnn will use the hidden states of the first layer
    proj2 = get_layer(options['encoder'])[1](tparams, proj1[0], options,
                                             prefix='encoder_2nd',
                                             mask=x_mask)


    # do the same thing for backward rnns and get projr2
    projr2 = ...

    # concatenate 2nd layer hidden states of forward and backward rnns
    ctx = concatenate([proj2[0], projr2[0][::-1]], axis=proj2[0].ndim-1)
```

For this to work, you also need to change the layer naming (prefix) and add second layer parameters, by doing:

``` python
    # encoder: 1st layer forward RNN
    params = get_layer(options['encoder'])[0](options, params,
                                              prefix='encoder_1st',
                                              nin=options['dim_word'],
                                              dim=options['dim'])
    # encoder: 2nd layer forward RNN
    params = get_layer(options['encoder'])[0](options, params,
                                              prefix='encoder_2nd',
                                              nin=options['dim'],
                                              dim=options['dim'])
```

Note that, above snippets are not tested.

**Comment by amirj** [comment]
I do appreciate your help.
It was really helpful.

**Comment by amirj** [comment]
I changed some functions in order to support a **4-layers bidirectional, attention-based encoder-decoder** model. 
I just worry about **the attention mechanism** when stacked multiple layers of decoders. 
Would you please review [the code](https://github.com/amirj/dl4mt-tutorial/commit/32f320dea7e44c0127997311673de8d0441239a9#diff-2b8111a635f5626bbbb2c7e30b5fcd99)?
Please let me know if you see something incorrect in the source code.

**Comment by orhanf** [comment]
@amirj your code seems to be fine (haven't tested tho, just skimmed it).

You seem to be attending to the last encoder annotations at each layer in the decoder, while each decoder layer is also a sequence model of the layer above. 

Stacking bidirectional encoders seems to be trivial but how do you stack the decoders (with attention), to my knowledge, is an open question, and probably has an empirical answer. 

May be someone else, who played with stacking decoders with attention can comment on that here.

**Comment by bastings** [comment]
@orhanf in your example, don't you want to give the **concatenated** states of layer 1 (both directions) as input to layer 2, etc? Instead of building a deep forward and a deep backward encoder separately.

**Comment by orhanf** [comment]
@bastings my example here is a **crude** implementation, just to show how you can stack recurrent layers. The specifics of how you do it, i guess, is a research question and perhaps has an empirical answer.

**Comment by bastings** [comment]
Thanks @orhanf .  I just wanted to note it since people might read this and only consider 1 option. There are basically 2 trivial ways to stack the encoder layers, and I think it might makes sense to do it in the way I described.
