### ISSUE TITLE
compare to groundhog

### ISSUE THREAD

**Issue by papar22** [kyunghyuncho/dl4mt-material#27]
Is it as accurate as groundhog in machine translation?

Thanks in advance

**Comment by orhanf** [comment]
It is indeed, many recent research using this codebase. Besides the implementation is cleaner and straightforward.

**Comment by papar22** [comment]
Thanks. one more question?
what are the file "setup_cluster_env.sh" and "setup_local_env.sh" for? If I wanna run the jobs on the cluster, what should I do? As it works on my machine, but it will be hanged while running on the cluster nodes. Your answer will be appreciated.

Thanks

**Comment by orhanf** [comment]
@papar22 those scripts are prepared for setting up the environments for dl4mt winter school. Submitting a job is a bit of cluster specific, so you may need to check [this](https://github.com/kyunghyuncho/dl4mt-material/blob/master/session2/train.sh) just as a reference to submit a job.
