### ISSUE TITLE
why decoupling 'rescore' from 'translate'?

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#28]
It seems that the role of 'restore_with_lm' is to rescoring the output of 'translate.py' using language model. Is it true?
I think the decoder ('translate.py') MUST leverage a language model in generating the output. Why these two modules have been decoupled?

**Comment by orhanf** [comment]
@amirj you are correct,`rescore_with_lm.py` is for rescoring the output of `translate.py` using a language model. 
The sessions are tried to be made incremental and self-contained, in order not to alter `translate.py`, they  are put in separate files. Feel free to combine them according to your requirements.
