### ISSUE TITLE
What's the difference between 'nmt.py' in session 2 and session 3?

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#29]
Unfortunately, following the difference in the source codes does not help me to solve the logical difference between 'nmt.py' in session 2 and session 3. Would you please describe the logical difference?

**Comment by orhanf** [comment]
@amirj `nmt.py` in session 2 and session 3 should be identical. Synched them [here](https://github.com/orhanf/blocks-examples/commit/a103c8a78647e1e40251fe69dc8ea670e90780f1), can you check that please? If it works i can merge it with the central.

**Comment by amirj** [comment]
@orhanf I don't understand the relation between [this link](https://github.com/orhanf/blocks-examples/commit/a103c8a78647e1e40251fe69dc8ea670e90780f1) and the topic!
By the way, when I diff 'nmt.py' in session 2 and session 3 it seems that they are different to some extent. For example: 

```
     shared_vars = [tparams[_p(prefix, 'U')],
                    tparams[_p(prefix, 'Wc')],
-                   tparams[_p(prefix, 'Wd_att')],
+                   tparams[_p(prefix, 'W_comb_att')],
                    tparams[_p(prefix, 'U_att')],
                    tparams[_p(prefix, 'c_tt')],
                    tparams[_p(prefix, 'Ux')],
-                   tparams[_p(prefix, 'Wcx')]]
+                   tparams[_p(prefix, 'Wcx')],
+                   tparams[_p(prefix, 'U_nl')],
+                   tparams[_p(prefix, 'Ux_nl')],
+                   tparams[_p(prefix, 'b_nl')],
+                   tparams[_p(prefix, 'bx_nl')]]
```

It seems that the attention mechanism has been changed in session3.

**Comment by orhanf** [comment]
lol, sorry my bad, i meant [this](https://github.com/orhanf/dl4mt-material/commit/9199ac05717f37b13694c4c8ce9d5d0938d746c6). Actually it was session2 that has changed, and session3 is not adapted for those changes.

**Comment by amirj** [comment]
Is it means that learning with the current version of nmt.py in session3 leads to incorrect results?

**Comment by orhanf** [comment]
Not incorrect results, actually the original version. Session2 implements an improved version tho.
