### ISSUE TITLE
hardcoded paths need to be fixed in nmt.py or train_nmt.py or both ?

### ISSUE THREAD

**Issue by vince62s** [kyunghyuncho/dl4mt-material#34]
Can someone please tell me if we need to fix both files ?

making changes in train_nmt.py seems to be ok, but not sure.

can you help ?
thanks.

**Comment by orhanf** [comment]
Hardcoded paths in `nmt.py` are just default parameters, and will be set to these default values only if you do not provide them in `train_nmt.py`. If you are specifying the paths, and the other parameters, in `train_nmt.py` then you don't need to change `nmt.py`
