### ISSUE TITLE
UNK replacement

### ISSUE THREAD

**Issue by vince62s** [kyunghyuncho/dl4mt-material#36]
Does a good will feel like implementing this promising [http://arxiv.org/pdf/1410.8206v4.pdf](http://arxiv.org/pdf/1410.8206v4.pdf) way to replace UNK using this code [https://github.com/sebastien-j/LV_groundhog/blob/master/experiments/nmt/replace_UNK.py](https://github.com/sebastien-j/LV_groundhog/blob/master/experiments/nmt/replace_UNK.py) ?

**Comment by kyunghyuncho** [comment]
@sebastien-j any chance you'll implement this here? :)

**Comment by vince62s** [comment]
is there a chance that the .pkl and .npz files are compatible with groundhog ?

**Comment by kyunghyuncho** [comment]
@vince62s Unfortunately, that is not going to be an easy job to do, and there's no plan for it.
