### ISSUE TITLE
Multi-Task Learning for Multiple Language Translation

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#40]
@kyunghyuncho 
Is it possible to easily extend this project to support [Multi-task learning in machine translation](http://www.aclweb.org/anthology/P15-1166)?

**Comment by amirj** [comment]
Woow, I see the following paper now. It is more interesting: [Multi-Way, Multilingual Neural Machine Translation with a Shared Attention Mechanism](http://arxiv.org/abs/1601.01073)

**Comment by kyunghyuncho** [comment]
@orhanf will soon release the code for multi-way, multilingual translation. The code will likely be in a separate repository, as we want to keep this repo as minimal as possible for the purpose of tutorial.
