### ISSUE TITLE
Preparing dataset for neural MT

### ISSUE THREAD

**Issue by arvind2505** [kyunghyuncho/dl4mt-material#47]
I want to train the Attention-based encoder-decoder model for machine translation (Session 2). It is unclear to me how to prepare the dataset for this. I tried running preprocess.sh in data/ with S=en and T=fr and specifying appropriate paths for P1 and P2. I get the following error:
./preprocess.sh: line 18: all_en-fr.en: No such file or directory
./preprocess.sh: line 19: all_en-fr.fr: No such file or directory
./preprocess.sh: line 23: all_en-fr.en.tok: No such file or directory
./preprocess.sh: line 26: all_en-fr.fr.tok: No such file or directory
./preprocess.sh: line 29: all_en-fr.en.tok: No such file or directory
./preprocess.sh: line 30: all_en-fr.fr.tok: No such file or directory

Are files all_en-fr.en and all_en-fr.fr need to be downloaded? Sorry if these questions are already answered and I didn't find it. Thanks for the help!

**Comment by orhanf** [comment]
Hi @arvind2505, 
Please first call `dl4mt-tutorial/data/download_files.py` and then `dl4mt-tutorial/data/preprocess.sh`
Cheers,

**Comment by arvind2505** [comment]
Thanks! This worked
