### ISSUE TITLE
What's the role of 'dim_word' parameter in the 'train()' method?

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#52]
It seems that a kind of embedding has been leveraged in nmt. Specially, there is a 'dim_word' parameter in the train() method. 
The embedding matrix has been defined in [the 'init_params()' method](https://github.com/nyu-dl/dl4mt-tutorial/blob/master/session2/nmt.py#L522-L524) but I don't understand the role of embedding in the architecture of Encoder or Decoder. I think that the representation of words is 1-of-K coding as described [here](https://devblogs.nvidia.com/parallelforall/introduction-neural-machine-translation-gpus-part-2/). Would you please clear why you're using this kind of embedding and the point of that?

**Comment by bastings** [comment]
The embedding is simply the first projection of the 1-of-K coded input vector. The nice thing here (and possibly the main reason) is that it is shared between both directions of the bi-directional encoder.

**Comment by kyunghyuncho** [comment]
@bastings thanks for answering this!
