### ISSUE TITLE
Do you have any plan for the next deep learning for machine translation school?

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#56]
I just interested to know if another deep learning for machine translation school will be available? 
when and where?
Is it possible to access 2016 winter school videos?

**Comment by kyunghyuncho** [comment]
There is no DL4MT summer/winter school planned (at least not that I know of,) but I will give two tutorials on neural MT this year:
- At ACL'16: https://sites.google.com/site/acl16nmt/ together with Chris Manning and Thang Luong
- At AMTA MT Summit '16

For the videos from the DL4MT Winter School in 2015, you should contact the organizers.

**Comment by amirj** [comment]
Thank you.
