### ISSUE TITLE
Why the grads have to be shared?

### ISSUE THREAD

**Issue by luochuwei** [kyunghyuncho/dl4mt-material#58]
We find in theano tutorial, the update in the theano function uses grads directly. 
However, in the "sgd" function in your code, the grads are put into gshared, could you tell me the reason?    Thank you!

**Comment by orhanf** [comment]
Hi @luochuwei,

We carry the gradients into shared variables just for debugging purposes (you can easily get their values, and plot the norm etc.). 

The downside is increased memory consumption (note that, this is a tutorial :wink: ). For large scale experiments, you may want to skip this step to save some memory, in that case you can check [here](https://github.com/nyu-dl/dl4mt-multi/blob/master/mcg/algorithm.py#L185-L194) for a reference implementation.

**Comment by luochuwei** [comment]
@orhanf Oh, I know. 
Thank you very much!
