### ISSUE TITLE
Unnecessary bias term?

### ISSUE THREAD

**Issue by jozef-mokry** [kyunghyuncho/dl4mt-material#67]
Is the bias term c_tt required here: 
(https://github.com/nyu-dl/dl4mt-tutorial/blob/master/session3/nmt.py#L458) ? I think the softmax that follows will cancel the effect of that bias.

**Comment by orhanf** [comment]
Hi @jozef-mokry , yes the bias term `c_tt` becomes obsolete but we keep it for backward compatibility (models trained before may cause problem with extra fields while loading)
