### ISSUE TITLE
How to build the dataset 'all.en.concat.gz.pkl' in session2/train_nmt_all.py?

### ISSUE THREAD

**Issue by wead-hsu** [kyunghyuncho/dl4mt-material#70]
Sorry, it may not be an issue. However, can you provide any idea about how to make the dataset?

**Comment by orhanf** [comment]
Hi @wead-hsu , please use the provided preprocessing script [here](https://github.com/nyu-dl/dl4mt-tutorial/blob/master/data/preprocess.sh), which will download and preprocess the necessary datasets for a sample run. Note that files with `*.pkl` extension are vocabulary files.
