### ISSUE TITLE
ValueError: unsupported pickle protocol: 3

### ISSUE THREAD

**Issue by hanyaqian** [kyunghyuncho/dl4mt-material#73]
`Traceback (most recent call last):
  File "./train_lm.py", line 41, in <module>
    'reload': [False]})
  File "./train_lm.py", line 27, in main
    use_dropout=params['use-dropout'][0])
  File "/mnt/f/Programing/dl4mt_codes/codes/dl4mt-tutorial/session0/lm.py", line 641, in train
    worddicts = pkl.load(f)
ValueError: unsupported pickle protocol: 3
`
i use the data of europarl-v7.fr-en suggest at #62 instead wiki data, and hanpen the problem above.

Thanks

**Comment by orhanf** [comment]
This seems like a python 2 - 3 compatibility issue. 

Please, try passing `protocol=2` to `pkl.dump(worddict, f, protocol=2)` when you create the vocabulary, [here](https://github.com/nyu-dl/dl4mt-tutorial/blob/master/data/build_dictionary.py#L39)

**Comment by hanyaqian** [comment]
Hi @orhanf , thank you for your reply in time! and now it works.
