### ISSUE TITLE
why  convert the value of matrix to the type with astype('float32')?

### ISSUE THREAD

**Issue by hanyaqian** [kyunghyuncho/dl4mt-material#74]
Hi~
the 106 lines of lm.py in session0, why to return the value of matrix of weight with type 'float32'?
this is a bit stupid question.
Thanks!

**Comment by orhanf** [comment]
Hi @hanyaqian, `float32` type is related with GPU. Please check [here](http://deeplearning.net/software/theano/tutorial/using_gpu.html) for a detailed description.

**Comment by hanyaqian** [comment]
@orhanf Thanks!
