### ISSUE TITLE
a detailed description about param_init_gru and gru_layer

### ISSUE THREAD

**Issue by hanyaqian** [kyunghyuncho/dl4mt-material#75]
Hi~
Where can i find a detailed description about param_init_gru and gru_layer in lm.py of session0, there are some difficult for me to understand those function.
Thanks!

**Comment by orhanf** [comment]
Hi @hanyaqian, `gru_layer` in session0 implements the basic version of gated recurrent unit, detailed descriptions can be found  at [[1]](https://arxiv.org/abs/1412.3555) and [[2]](https://arxiv.org/abs/1406.1078).

**Comment by hanyaqian** [comment]
Hi @orhanf 
Thank you for recommending the papers, I will read them carefully, and  thank you for your work!
