### ISSUE TITLE
the value of TensorType(float32, 3D)

### ISSUE THREAD

**Issue by hanyaqian** [kyunghyuncho/dl4mt-material#76]
Hi
How can i print the value of emb and emb_shifted in 365 lines of lm.py? so i can clearly know what hanppened. I find the .eval() and theano.pp() do not work. this is also a bit stupid question.
Thanks!

**Comment by orhanf** [comment]
Hi @hanyaqian, this is more related with theano, but easiest way is, returning `emb` and `emb_shifted` from `build_model`, and compile the theano [function](https://github.com/nyu-dl/dl4mt-tutorial/blob/master/session0/lm.py#L705) with these additional variables.

**Comment by hanyaqian** [comment]
@orhanf , I will try it, thank you very much!
