### ISSUE TITLE
compute word probabilities

### ISSUE THREAD

**Issue by hanyaqian** [kyunghyuncho/dl4mt-material#77]
Hi~
i have some difficult in understanding the part of compute word probabilities in session. Can you recommend some document for me? 
Thanks!

**Comment by orhanf** [comment]
Hi @hanyaqian, the best document to review would be Prof. Cho's [lecture notes](https://github.com/nyu-dl/NLP_DL_Lecture_Note) and it's references.

**Comment by hanyaqian** [comment]
Hi @orhanf , the document you recommend is very detailed, thank you!
